name: Publish Ironclad.Noise to NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Extract Version From .nuspec
        id: extract_version
        run: |
          version=$(grep -oPm1 "(?<=<version>)[^<]+" Ironclad.Noise.nuspec)
          echo "version=$version" >> $GITHUB_ENV

      - name: Check if Version Exists Already
        run: |
          exists=$(curl -s https://api.nuget.org/v3-flatcontainer/Ironclad.Noise/${{ env.version }}/index.json | grep -c '404')
          if [ "$exists" -eq 0 ]; then
            echo "Error: Version ${{ env.version }} already exists on NuGet."
            exit 1
          fi

      - name: Run Unit Tests
        run: dotnet test --configuration Release

      - name: Pack
        run: dotnet pack --configuration Release

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push **/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
